services:
  - type: web
    name: peblo-notes-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: static
    name: peblo-notes-frontend
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /shared/*
        destination: /shared.html
